import { createRouter } from "@tanstack/react-router";
/* import { routeTree } from "./routeTree.gen"; */
// routeTree file was automatically generated by TanStack Router.

export function getRouter() {
  const router = createRouter({
    /*routeTree,*/
    scrollRestoration: true,
    defaultPreload: "intent",
    /*  defaultPreloadStaleTime: 0, */

    /* 
     context: {
    queryClient: undefined!,
  },
   */
  });

  return router;
}

/* 

in app

<RouterProvider
  router={router}
  context={{
    queryClient,
  }}
/>

This queryClient in router context is the piece that connects TanStack Router loaders to your existing apiQueries setup.


| Option                       | What it does                                                                             |
| ---------------------------- | ---------------------------------------------------------------------------------------- |
| `scrollRestoration: true`    | Restores previous scroll position when navigating back/forward                           |
| `defaultPreload: "intent"`   | Preloads route when user hovers or focuses a link                                        |
| `defaultPreloadStaleTime: 0` | Preloaded data becomes stale immediately; often used when TanStack Query manages caching |




# What You Should Learn First

## Must know

✅ `context`

✅ `scrollRestoration`

✅ `defaultPreload`

✅ `defaultPreloadStaleTime`

✅ `defaultNotFoundComponent`

---

## Learn later

✅ `defaultPendingComponent`

✅ `defaultErrorComponent`

---

## Advanced

✅ `basepath`

✅ `defaultViewTransition`

✅ `routeMasks`

✅ `defaultStructuralSharing`

---

If you're building a React + TanStack Query app, the most valuable next topic after routing basics is actually **router context + `beforeLoad` guards**. That's where authentication, permissions, and route protection become really powerful.


*/

declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof getRouter>;
  }
}
